### ISSUE TITLE
zoo layout

### ISSUE THREAD

**Issue by xrkffgg** [zoo-js/zoo-layout#1]
目前 issue charts 网站布局接近

拟将布局提出公共，如一般的 heade footer，支持参数，自定义 render

main 可以 空出来 由各项目自定义处理。

**Comment by ajuner** [comment]
我建议是放一个项目里是不是好点

**Comment by xrkffgg** [comment]
不用放一个，万一以后有其他玩的，不能都放一起啊。

做一个 Layout  组件，其他组件 传参 直接快速生成页面。

**Comment by ajuner** [comment]
好嘞

**Comment by ajuner** [comment]
提交了下  npm还没发

**Comment by xrkffgg** [comment]
OK  我下午瞅瞅
